### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by TerribleDev** [paybyphone/spectator#7]
Could you add this to chocolatey.org ?

**Comment by TerribleDev** [comment]
if I make MSI's and choco packages for this...would they be accepted/pulled in?

**Comment by plmwong** [comment]
Hi there, sorry for the delay. Automation for building installation MSIs and the nuspec/powershell required for Chocolatey support are both things that we'd definitely like to have. If you're willing to contribute them, then that would be great!

**Comment by TerribleDev** [comment]
Yeah...most certainly going to do that...I already have a wix msi that works...so things are moving along here...

**Comment by TerribleDev** [comment]
I'll add it as part of the cake build.

**Comment by plmwong** [comment]
Thanks man, much appreciated.

**Comment by plmwong** [comment]
Manually pushed 1.0.0 release to Chocolatey (pending submission review). Automated CI build to build, package and publish will be done as a separate task.
