### ISSUE TITLE
Queston: base-spectator-config.json reload

### ISSUE THREAD

**Issue by TerribleDev** [paybyphone/spectator#8]
Hi, if the `base-spectator-config.json` file changes does spectator automatically reload the file into memory? or is it expected to restart the service if you edit the file during its operation.

**Comment by plmwong** [comment]
Yes, the `base-spectator-config.json` ought to be reloaded from file when the configuration is re-read (expiration interval is configured through the `Spectator.ConfigurationRefresh` app setting).
